Controllers/MessagingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WindTalkerMessenger.Models.DataLayer;
using WindTalkerMessenger.Services;

namespace WindTalkerMessenger.Controllers
{
	public class MessagingController : Controller
	{
		private readonly OnlineUsersLists _onlineUsersLists;
		private readonly IHttpContextAccessor _http;
		private readonly IUserNameService _userNameService;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ILogger<MessagingController> _logger;
		private const string chatNameKey = "chatName";

		public MessagingController(OnlineUsersLists onlineUsersLists,
                                   IHttpContextAccessor http,
								   IUserNameService userNameService,
								   UserManager<ApplicationUser> userManager,
								   ILogger<MessagingController> logger)
        {
			_onlineUsersLists = onlineUsersLists;
			_http = http;
			_userNameService = userNameService;
			_userManager = userManager;
			_logger = logger;
		}

		public IActionResult Guest(string chatName)
		{
			_http.HttpContext.Session.SetString("chatName", chatName);

			return View("Views\\Messaging\\ChatPage.cshtml");
		}



        [HttpPost]
        [Route("/GetLoginState/{chatName}")]
        public bool GetLoginState(string chatName)
        {
			string userLoginState;
			_onlineUsersLists.userLoginState.TryGetValue(chatName, out userLoginState);
			bool state = true;

			if(userLoginState != null) 
			{ 
				if(userLoginState == "Guest")
				{
					state = false;
				}
			}
            return state;
        }

		[HttpPost]
		[Route("/SetGuestChatName/ChatName/{chatName}")]
		public void SetGuestChatName(string chatName)
		{
			try 
			{
				_http.HttpContext.Session.SetString(chatNameKey, chatName);
			}catch(Exception ex)
			{
				_logger.LogError($"New Guest Chat Name Could Not Be Set: {ex}");
			}
		}

		public async Task<bool> GetReceiverRegistrationState(string receiverChatName)
		{
			bool state = true;
			var registeredUsers = await _userManager.Users.Select(u => u.UserName).ToListAsync();
			if (!registeredUsers.Contains(receiverChatName))
			{
				state = false;
			}

			return state;
		}

        public IActionResult StartChatting()
		{
			if (_userNameService.IsUserAuthenticated())
			{
				return View("Views\\Messaging\\ChatPage.cshtml");
			}
			else
			{
				return View("Views\\Messaging\\ChatOptions.cshtml");

			}
		}
		[HttpPost]
        public async Task<IActionResult> KillSwitchAsync(string userName)
		{
			await _userNameService.KillSwitchAsync(userName);

			return Redirect(("~/"));
		}

        [HttpPost]
        [Route("/IsReceiverRegistered/{username}")]
        public async Task<bool> IsReceiverRegistered(string username)
        {
			var isRegistered = await _userNameService.IsUserRegistered(username);

			return isRegistered;

        }

		[HttpPost]
        [Route("/CheckChatName/CheckName/{chatName}")]
        public async Task<bool> CheckChatName(string chatName)
        {
			var registeredChatNames = await _userNameService.GetAllUserNames();

			if((registeredChatNames.Contains(chatName)) || (_onlineUsersLists.anonUsers.TryGetValue(chatName,out _))) 
			{
				return true;
			}

            return false;
		}

    }
}

Views/Messaging/ChatOptions.cshtml
@using WindTalkerMessenger.Models.DataLayer
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<div class="containerBase">
    <div class="text-center">

@if (!SignInManager.IsSignedIn(User))
{
            <a class="enterButton" asp-area="Identity" asp-page="/Account/Login">Login</a>
            <a class="enterButton" sp-area="Identity" asp-page="/Account/Register">Register</a>
    <p>Or you can pick a guest name and then click "Start Chatting".</p>
    <form asp-action="Guest" asp-controller="Messaging" method="post" id="guest_form">
            <input type="text" placeholder="Pick Chat Name" class="username" name="chatName" id="chatName" />
                <button type="submit" class="enterButton" id="submitButton" name="guestSend">Start Chatting</button>
                <div id="guestError"></div>
            </form>
}
else
{
            <form asp-action="Guest" asp-controller="Messaging" method="post" id="guest_form">
                <span id="guestError"></span>
                <input type="text" placeholder="Pick Chat Name" name="chatName" id="chatName" />
                <button type="submit" class="enterButton" id="submitButton" name="guestSend">Start Chatting</button>
            </form>
}
</div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>


<script>
    //https://stackoverflow.com/questions/57328836/post-fetch-net-core

    $("#submitButton").click(async function (event) {
        event.preventDefault();
        const chatName = $("#chatName").val().trim();
        const request = `/CheckChatName/CheckName/${chatName}`
        await fetch(request, {
            method: 'POST',
            body: JSON.stringify({ ChatName: chatName }),
            headers: {
                'Accept': 'application/json; charset=utf-8',
                'Content-Type': 'application/json;charset=UTF-8'
            }
        })
            .then(response => response.json())
            .then(response => nameCheck(response, chatName))
            .catch(error => caughtErrors(error))
    });
    function valueCheck(chatName) {
        if (chatName == "") {
            $("#guestError").text("Please enter a username.");
            $("#chatName").focus();
        }

    }
    function nameCheck(response, chatName) {
        if (response == true) {
            $("#guestError").text("That chat name is taken.");
        } else {
            sessionStorage.setItem('UserChatName', chatName);
            console.log("set");
            $("#guest_form").submit();
        }
    }

    const caughtErrors = (error) => {
        console.log(error.toString());
    }
</script>

Views/Messaging/ChatPage.cshtml
@using System.Security.Claims
@using WindTalkerMessenger.Models.DataLayer
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<html>
<head>
	<!-- Import this CDN to use icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" /></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.13/signalr.min.js" /></script>

	<style>
		button {
			border-radius: 5px;
			width: 100%;
		}
		#li {
			display: inline-block;
			width: 100%;
		}
		body {
			background-image: url('../banner.jpg');
			background-repeat: no-repeat;
			background-attachment: fixed;
			background-size: 100% 100%;
		}
		.containerBase{
			margin-top:100px;
		}
	</style>
</head>

<body>
	<div class="containerBase">
		<div>
		</div>
		<div id="chat-page">
			<div class="maindiv">
				<div id="reversal">
					<ul id="leftinnerdiv">
					</ul>
					<div id="rightinnerdiv">
						<p id="chatParagraph">Options</p>
						<p>Enter a Username below to begin new chat.</p>
						<input type="text"
							   id="username"
							   class="username"
							   placeholder="Username" />
						@if (SignInManager.IsSignedIn(User))
						{
							<p>To delete your PROFILE and CHAT HISTORY click the "Kill Switch" below.</p>

							<p><span id="warning">WARNING:</span> THIS ACTION IS NOT REVERSABLE!</p>
							<button class="enableSwitch"
							id="enableSwitch"
							name="enableSwitch">
								Enable Kill Switch
							</button>

							<form asp-controller="Messaging" asp-action="KillSwitch">
								<input type="hidden" name="userName" value="@User.Identity.Name" />
								<button class="killswitch"
								id="killswitch"
								type="submit"
								disabled>
									Kill Switch
								</button>
							</form>
						}else{
							<p>Register or Login for the Kill Switch!</p>
						}
					</div>
				</div>
				@if (SignInManager.IsSignedIn(User))
				{
					<div id="chatsAside">
						<p id="chatParagraph">Chats</p>
						<ul id="chatList">
						</ul>
					</div>
				}else{
					<div id="chatsAside">
						<p id="chatParagraph">Chats</p>
						<p>Register or Login for a Chat List!</p>
						<p>Because you are just a guest you can only
						   chat with one person at a time.
						</p>
					</div>
				}
			</div>
			<div class="msg-bottom" id="messageContainer">
				<div class="input-group">
					<input type="text"
						   id="message"
						   class="form-control"
						   placeholder="Write message..." />
				</div>
				<button class="sendButton" id="sendButton">Transmit</button>
			</div>
		</div>
	</div>
</body>
</html>